steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tonal-run-241311/mymicroservicenode', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tonal-run-241311/mymicroservicenode']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mymicroservicenode', 'mymicroservicenode=gcr.io/tonal-run-241311/mymicroservicenode']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
tags: ['drteste', 'mymicroservicenode']
images: ['gcr.io/tonal-run-241311/mymicroservicenode']